Part 4

PRESIDENTS

Scrape the list of US Presidents from https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_StatesLinks to an external site.. using pandas and save them as a CSV.

Tips

This requires headers and pandas, which is different than the one above.

Part 1 - testing using request + BeautifulSoup
Check for 
response.status_code for 200 response = URL + header building was successful for the query

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 
}

response = requests.get('https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States', headers=headers)

doc = BeautifulSoup(response.text, 'html.parser')

In [12]:
response.status_code  # 200 means OK

200

Part 2 
-> Use panda to build URL + Header 
-> use panda's: read_html

pd.read_html(): find and parse HTML tables.

In [60]:
import pandas as pd

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

tables = pd.read_html(
    'https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States',
    storage_options=headers
)

tables

[    No.[a]  Portrait                    Name (birth–death)  \
 0        1       NaN    George Washington (1732–1799) [19]
 1        1       NaN    George Washington (1732–1799) [19]
 2        2       NaN           John Adams (1735–1826) [21]
 3        3       NaN     Thomas Jefferson (1743–1826) [23]
 4        3       NaN     Thomas Jefferson (1743–1826) [23]
 ..     ...       ...                                   ...
 78      44       NaN           Barack Obama (b. 1961) [75]
 79      44       NaN           Barack Obama (b. 1961) [75]
 80      45       NaN  Donald Trump (b. 1946) 1st term [76]
 81      46       NaN              Joe Biden (b. 1942) [77]
 82      47       NaN  Donald Trump (b. 1946) 2nd term [76]

                                Term[16]  Party[b][17]          Party[b][17].1  \
 0        April 30, 1789 – March 4, 1797           NaN            Unaffiliated
 1        April 30, 1789 – March 4, 1797           NaN            Unaffiliated
 2         March 4, 1797 – March 4, 1801           NaN              Federalist
 3         March 4, 1801 – March 4, 1809           NaN  Democratic- Republican
 4         March 4, 1801 – March 4, 1809           NaN  Democratic- Republican
 ..                                  ...           ...                     ...
 78  January 20, 2009 – January 20, 2017           NaN              Democratic
 79  January 20, 2009 – January 20, 2017           NaN              Democratic
 80  January 20, 2017 – January 20, 2021           NaN              Republican
 81  January 20, 2021 – January 20, 2025           NaN              Democratic
 82         January 20, 2025 – Incumbent           NaN              Republican

    Election   Vice President[18]
 0   1788–89        John Adams[c]
 1      1792        John Adams[c]
 2      1796  Thomas Jefferson[d]
 3      1800           Aaron Burr
 4      1804       George Clinton
 ..      ...                  ...
 78     2008            Joe Biden
 79     2012            Joe Biden
 80     2016           Mike Pence
 81     2020        Kamala Harris
 82     2024             JD Vance

 [83 rows x 8 columns],
   vtePresidents of the United States  \
 0        Presidents and presidencies
 1               Presidency timelines
 2                     Category  List

                 vtePresidents of the United States.1
 0  George Washington (1789–1797) John Adams (1797...
 1  Washington J. Adams Jefferson Madison Monroe J...
 2                                     Category  List  ,
    vteLists related to presidents and vice presidents of the United States  \
 0          List of presidents List of vice presidents
 1                                          Presidents
 2                                 Professional career
 3                                       Personal life
 4                               Depictions and honors
 5                                     Vice presidents
 6                                          Succession
 7                                           Elections
 8                                          Candidates
 9                               Political affiliation
 10                                       Distinctions

    vteLists related to presidents and vice presidents of the United States.1
 0          List of presidents List of vice presidents
 1   Professional career Approval rating Assassinat...
 2   Approval rating Assassination attempts and plo...
 3   Age Ancestry Bibliographies autobiographies Bu...
 4   Actor portrayals fictional Currency Educationa...
 5   Age Burial places Coats of arms Education Home...
 6   Acting presidents Designated survivors Inaugur...
 7   Electoral College margin Popular vote margin W...
 8   Political affiliation Democratic Democratic-Re...
 9   Democratic Democratic-Republican Federalist Gr...
 10  African American Campaign slogans Female Heigh...                         ,
                        0                                                  1
 0    Professional career  Approval rating Assassination attempts and plo...
 1          Personal life  Age Ancestry Bibliographies autobiographies Bu...
 2  Depictions and honors  Actor portrayals fictional Currency Educationa...,
                        0                                                  1
 0  Political affiliation  Democratic Democratic-Republican Federalist Gr...
 1           Distinctions  African American Campaign slogans Female Heigh...,
   vteChief executives of the United States  \
 0                                  Federal
 1           State governors (current list)
 2               Territorial (current list)
 3                                  Defunct
 4                             Demographics

           vteChief executives of the United States.1
 0                President of the United States list
 1  Alabama list Alaska Arizona Arkansas Californi...
 2  American Samoa District of Columbia list Guam ...
 3  Cuba Dakota Territory Panama Canal Zone Philip...
 4  Current by age longest-serving Ethnic-minority...  ]

In [61]:
len(tables)

6

In [64]:
# tables is a list — pick the one you want, e.g.:
df = tables[0]

In [65]:
df.head(5)

,No.[a],Portrait,Name (birth–death),Term[16],Party[b][17],Party[b][17].1,Election,Vice President[18]
0,1,NaN,George Washington (1732–1799) [19],"April 30, 1789 – March 4, 1797",NaN,Unaffiliated,1788–89,John Adams[c]
1,1,NaN,George Washington (1732–1799) [19],"April 30, 1789 – March 4, 1797",NaN,Unaffiliated,1792,John Adams[c]
2,2,NaN,John Adams (1735–1826) [21],"March 4, 1797 – March 4, 1801",NaN,Federalist,1796,Thomas Jefferson[d]
3,3,NaN,Thomas Jefferson (1743–1826) [23],"March 4, 1801 – March 4, 1809",NaN,Democratic- Republican,1800,Aaron Burr
4,3,NaN,Thomas Jefferson (1743–1826) [23],"March 4, 1801 – March 4, 1809",NaN,Democratic- Republican,1804,George Clinton

In [66]:
#rename columns 

df = df.rename(columns={df.columns[7]: "Vice President"})

In [67]:
df

,No.[a],Portrait,Name (birth–death),Term[16],Party[b][17],Party[b][17].1,Election,Vice President
0,1,NaN,George Washington (1732–1799) [19],"April 30, 1789 – March 4, 1797",NaN,Unaffiliated,1788–89,John Adams[c]
1,1,NaN,George Washington (1732–1799) [19],"April 30, 1789 – March 4, 1797",NaN,Unaffiliated,1792,John Adams[c]
2,2,NaN,John Adams (1735–1826) [21],"March 4, 1797 – March 4, 1801",NaN,Federalist,1796,Thomas Jefferson[d]
3,3,NaN,Thomas Jefferson (1743–1826) [23],"March 4, 1801 – March 4, 1809",NaN,Democratic- Republican,1800,Aaron Burr
4,3,NaN,Thomas Jefferson (1743–1826) [23],"March 4, 1801 – March 4, 1809",NaN,Democratic- Republican,1804,George Clinton
...,...,...,...,...,...,...,...,...
78,44,NaN,Barack Obama (b. 1961) [75],"January 20, 2009 – January 20, 2017",NaN,Democratic,2008,Joe Biden
79,44,NaN,Barack Obama (b. 1961) [75],"January 20, 2009 – January 20, 2017",NaN,Democratic,2012,Joe Biden
80,45,NaN,Donald Trump (b. 1946) 1st term [76],"January 20, 2017 – January 20, 2021",NaN,Republican,2016,Mike Pence
81,46,NaN,Joe Biden (b. 1942) [77],"January 20, 2021 – January 20, 2025",NaN,Democratic,2020,Kamala Harris
82,47,NaN,Donald Trump (b. 1946) 2nd term [76],"January 20, 2025 – Incumbent",NaN,Republican,2024,JD Vance